name: Node and React CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install Dependencies for Server
        working-directory: spotaroom_server
        run: npm install

      - name: Install Dependencies for Client
        working-directory: spotaroom_client
        run: npm install
